services:
  web:
    build: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "--request", "HEAD", "--url", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
