services:
  web:
    build: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - GOWORK=off
    healthcheck:
      test: ["CMD", "curl", "-f", "--url", "http://localhost:3000/livez"]
      interval: 30s
      timeout: 5s
      retries: 5
