@startuml main flow

title 主要流程圖

start
:開啟遊戲主程式;
repeat
  :操作主選單;
  note right
    按鈕選項：
    - 開始遊戲 Play
    - 遊戲說明 Help
    - 設定 Setting
    - 退出遊戲 Exit
  end note
  if (建立遊戲) then (是)
    :設定遊戲參數;
  (否) elseif (加入遊戲) then (是)
  else (否)
    :退出遊戲;
    stop
  endif
  repeat
    :等待玩家加入;
  repeatwhile (人數足夠) is (否) not (是)
  :遊戲開始;
  :遊戲進行;
  :遊戲結束;
  :顯示遊戲結果;
repeatwhile (返回主選單)

@enduml
