@startuml play flow
(*) -down-> "打開主程式"
-down-> "顯示主選單"

if "操作主選單" then
  -down->[退出遊戲] (*)
else
  -down->[建立新對局] "顯示遊戲參數設定"
-down-> "設定遊戲參數"
-down->[進入遊戲] "顯示遊戲畫面"
-down-> "回合開始"
-down-> "玩家行動"
-down-> "回合結束"

if "將軍" then
  -up->[是] "遊戲結束"
  -up->[點擊確認回到主頁面] "顯示主選單"
else
  -up->[否] "輪到下一位玩家"
  -down-> "回合開始"
endif

@enduml