[database]
default = "gungi"

[database.connections.gungi]
driver = "sqlite"
database = "database/gungi.db"

[logger.slog]
path = "log/slog.log"
append = true

[logger.gorm]
path = "log/gorm.log"
append = false
