FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Gungi

# Data Structures

## User (object)

+ id: 22 (number)
+ name: LoveSnowEx (string)

## Player (User)

+ color (Color)

## Color (enum)

+ BLACK
+ WHITE

## Phase (enum)

+ LOBBY
+ PREPARATION
+ PLAYING
+ ENDED

## PieceType (enum)

+ MARSHAL
+ GENERAL
+ LIEUTENANT_GENERAL
+ MAJOR_GENERAL
+ SAMURAI
+ LANCER
+ KNIGHT
+ SPY
+ FORTRESS
+ PAWN
+ CANNON
+ MUSKETEER
+ ARCHER
+ CAPTAIN

## Piece (object)

+ type: Pawn (PieceType)
+ color: BALCK (Color)
+ position: 23 (number)

## Game (object)

+ id: 7 (number)
+ players (array)
    - (Player)
    - (User)
        + id: 1 (number)
        + name: GungiMaster (string)
        + color: WHITE (Color)
+ pieces (array)
    - (Piece)
    - (Piece)
        + type: Archer (PieceType)
        + color: White (Color)
        + position: 112 (number)
+ turn: WHITE (Color)
+ phase: SETUP (string)
+ winner (Color, nullable)

# Group User

## Users Collection [/api/users]

### Get User [GET /api/users/{id}]

+ Parameters
    + id (required, number, `1`) ... ID of the user

+ Response 200 (application/json)
    + Attributes (User)

+ Response 404 (application/problem+json)
    + Attributes
        + title: User not found (string)

### Create User [POST]

+ Request (application/json)
    + Attributes
        + name: LoveSnowEx (string)

+ Response 201 (application/json)
    + Headers

            Location: /api/users/22
    + Attributes (User)

# Group Game

## Games Collection [/api/games]

### Get Game [GET /api/games/{id}]

+ Parameters
    + id (required, number, `1`) ... ID of the game

+ Response 200 (application/json)
    + Attributes (Game)

+ Response 404 (application/problem+json)
    + Attributes
        + title: Game not found (string)

### Create Game [POST]

+ Response 201 (application/json)
    + Headers

            Location: /api/games/7
    + Attributes (Game)

### Join Game [POST /api/games/{id}/join]

+ Parameters
    + id (required, number, `1`) ... ID of the game

+ Request (application/json)
    + Attributes
        + user_id: 22 (number)
        + color: BLACK (Color)

+ Response 200 (application/json)
    + Attributes (Game)

+ Response 404 (application/problem+json)
    + Attributes
        + title: Game not found (string)

+ Response 409 (application/problem+json)
    + Attributes
        + title: Game is full (string)

### Leave Game [POST /api/games/{id}/leave]

+ Parameters
    + id (required, number, `1`) ... ID of the game

+ Request (application/json)
    + Attributes
        + user_id: 22 (number)

+ Response 200 (application/json)
    + Attributes (Game)

+ Response 404 (application/problem+json)
    + Attributes
        + title: Game not found (string)

+ Response 409 (application/problem+json)
    + Attributes
        + title: User is not in the game (string)

### Start Game [POST /api/games/{id}/start]

+ Parameters
    + id (required, number, `1`) ... ID of the game

+ Response 200 (application/json)
    + Attributes (Game)

+ Response 404 (application/problem+json)
    + Attributes
        + title: Game not found (string)
